In [10]:
import numpy as np

In [11]:
i = [1, 2, 3, 4, 5, 6]
j = [2, 3, 4, 5, 6, 7]
k = [7, 8, 9, 6, 5, 4]

In [12]:
matrix = [i, j, k]

In [13]:
print(matrix)

[[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7], [7, 8, 9, 6, 5, 4]]


In [14]:
print(matrix[1:2])

[[2, 3, 4, 5, 6, 7]]


In [15]:
i + j

[1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7]

In [16]:
narr = np.array([1, 2, 3])
narr

array([1, 2, 3])

In [17]:
narr.resize((4, 4), refcheck=False)
narr

array([[1, 2, 3, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
print(narr.shape)
print(narr.size)
print(narr.ndim)

(4, 4)
16
2


In [19]:
mat = np.zeros((4, 4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
mat = np.ones((4, 4), int)
mat

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
mat = np.array(([1, 2, 3], [9, 8, 7], [6, 5, 4]))
mat

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [22]:
reshaped_mat = mat.reshape(1, mat.size) ** 2
reshaped_mat.reshape(3, 3)

array([[ 1,  4,  9],
       [81, 64, 49],
       [36, 25, 16]])

In [23]:
np.array(i) - np.array(j)

array([-1, -1, -1, -1, -1, -1])

In [24]:
mat1 = np.array(([1.45, 2, 3], [4, 5.7, 6], [5, 6, 7], [4.2, 5.2, 6], [1, 2, 6.3], [8, 9.6, 7]))
mat2 = np.array(([4.2, 5.2, 6], [1, 2, 6.3], [8, 9.6, 7], [1.45, 2, 3], [4, 5.7, 6], [5, 6, 7]))
mat = mat1.dot(mat2.T).astype('float64')
mat

array([[ 34.49  ,  24.35  ,  51.8   ,  15.1025,  35.2   ,  40.25  ],
       [ 82.44  ,  53.2   , 128.72  ,  35.2   ,  84.49  ,  96.2   ],
       [ 94.2   ,  61.1   , 146.6   ,  40.25  ,  96.2   , 110.    ],
       [ 80.68  ,  52.4   , 125.52  ,  34.49  ,  82.44  ,  94.2   ],
       [ 52.4   ,  44.69  ,  71.3   ,  24.35  ,  53.2   ,  61.1   ],
       [125.52  ,  71.3   , 205.16  ,  51.8   , 128.72  , 146.6   ]])

In [25]:
mat.argmax()

32

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
type(mat[-1][0])

numpy.float64

In [28]:
mat[-3:, -3:][-1][-1]

146.6

In [29]:
mat >= 100

array([[False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False,  True, False, False,  True],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [ True, False,  True, False,  True,  True]])

In [30]:
mat[mat >= 100]

array([128.72, 146.6 , 110.  , 125.52, 125.52, 205.16, 128.72, 146.6 ])

In [31]:
import time

In [32]:
def pure_python():
    t1 = time.time()
    x = range(100000000)
    y = range(100000000)
    z = list()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t2 = time.time()
    return t2 - t1

In [33]:
pure_python()

23.350624561309814

In [34]:
def numpy_python():
    t1 = time.time()
    x = np.arange(100000000)
    y = np.arange(100000000)
    z = x + y
    t2 = time.time()
    return t2 - t1

In [35]:
numpy_python()

0.5756211280822754